[env]
# all workspace members can use this Makefile
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"
PORT = "8000"

# ---- GENERAL ----

[tasks.verify]
description = "Format, lint with Clippy and run tests"
dependencies = ["fmt", "clippy", "test_h_firefox"]

[tasks.verify_only]
description = "Like `verify`, but fails if the code isn't formatted. Primarily for CI."
dependencies = ["fmt_check", "clippy", "test_h_firefox"]

[tasks.bundle]
description = "Bundle the app into `/dist` folder"
dependencies = ["less_compile", "build_release", "wasm_opt"]
command = "cargo"
args = ["play", "scripts/bundle.rs"]

# ---- LESS ----

[tasks.less_compile]
description = "Compile LESS"
script_runner = "@shell"
script = [
'''
npm run less:compile
'''
]

[tasks.watch_less]
description = "Watch LESS"
script_runner = "@shell"
script = [
'''
npm run less:watch
'''
]

# ---- BUILD & CREATE WASMS ----
[tasks.compile]
description = "Build"
workspace = false
command = "cargo"
args = ["build"]

[tasks.compile_release]
description = "Build, with the --release flag"
workspace = false
command = "cargo"
args = ["build", "--release"]

[tasks.create_wasm]
description = "Build with wasm-pack"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V", min_version = "0.8.0" }
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "package", "--dev"]

[tasks.create_wasm_release]
description = "Build with wasm-pack"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V", min_version = "0.8.0" }
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "package"]

[tasks.build]
description = "Build, and create wasms"
workspace = false
dependencies = ["compile", "create_wasm"]

[tasks.build_release]
description = "Build, and create wasms, with the release flag"
workspace = false
dependencies = ["compile_release", "create_wasm_release"]

[tasks.watch]
description = "Build, create wasms, and watch/recompile files for changes"
workspace = false
dependencies = ["build", "create_wasm"]
watch = { ignore_pattern="pkg/*" }

[tasks.serve]
description = "Start server"
install_crate = { crate_name = "microserver", binary = "microserver", test_arg = "-h" }
workspace = false
command = "microserver"
args = ["--port", "${PORT}"]

[tasks.serve_dist]
description = "Start server in dist directory"
install_crate = { crate_name = "microserver", binary = "microserver", test_arg = "-h" }
workspace = false
command = "microserver"
args = ["--port", "${PORT}", "dist"]

[tasks.start]
description = "Combine the build and serve tasks"
workspace = false
dependencies = ["build", "serve"]

[tasks.wasm_opt]
description = "Optimize `package_bg.wasm` by `wasm_opt`"
script_runner = "@shell"
script = [
'''
npm run wasm:opt
'''
]

# ---- TEST ----

[tasks.test]
description = "Run tests. Ex: 'cargo make test firefox'. Test envs: [chrome, firefox, safari]"
clear = true
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["test", "--${@}"]

[tasks.test_release]
extend = "test"
description = "Run tests in release mode. Ex: 'cargo make test_release firefox'. Test envs: [chrome, firefox, safari]"
args = ["test", "--${@}", "--release"]

[tasks.test_h]
description = "Run headless tests. Ex: 'cargo make test_h firefox'. Test envs: [chrome, firefox, safari]"
extend = "test"
args = ["test", "--headless", "--${@}"]

[tasks.test_h_firefox]
description = "Run headless tests with Firefox."
extend = "test"
args = ["test", "--headless", "--firefox"]

[tasks.test_h_release]
extend = "test_h"
description = "Run headless tests in release mode. Ex: 'cargo make test_h firefox'. Test envs: [chrome, firefox, safari]"
args = ["test", "--headless", "--${@}", "--release"]

[tasks.test_one]
description = "Run a single test in Firefox. Ex 'cargo make test_one my_test'"
clear = true
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["test", "--firefox", "--", "--lib", "${@}"]

[tasks.test_one_h]
description = "Run a single test in headless Firefox. Ex 'cargo make test_one_h my_test'"
clear = true
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"

# ---- LINT ----

[tasks.fmt]
description = "Format with nightly rustfmt"
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--all"]

[tasks.fmt_check]
extend = "fmt"
description = "Check format with nightly rustfmt"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy]
description = "Lint with Clippy"
clear = true
install_crate = { rustup_component_name = "clippy", binary = "cargo-clippy", test_arg = "--help" }
command = "cargo"
args = ["clippy", "--all-features", "--", "--deny", "warnings", "--deny", "clippy::pedantic", "--deny", "clippy::nursery"]
